services:
  - type: web
    name: dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app_clean.py --server.port=$PORT --server.address=0.0.0.0"
